### PR TITLE
Add instruction for failed pip-installation

### PR DESCRIPTION
**Pull request by nadja-mansurov**
## Description
Added additional instruction to documentation. Without it an installation failed with the message: 
> ERROR: Could not find a version that satisfies the requirement dynophores
> ERROR: No matching distribution found for dynophores

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
Hi @nadja-mansurov, 

Thank you for reporting this!

I am getting your error in two cases:

__Case 1__
```bash
(test) dominique@c: ~/Documents/dynophores-master
$ ls -l
total 104
-rw-r--r-- 1 dominique dominique  3562 Mar  5 18:18 CODE_OF_CONDUCT.md
-rw-r--r-- 1 dominique dominique  1073 Mar  5 18:18 LICENSE
-rw-r--r-- 1 dominique dominique   117 Mar  5 18:18 MANIFEST.in
-rw-r--r-- 1 dominique dominique  2410 Mar  5 18:18 README.md
drwxr-xr-x 5 dominique dominique  4096 Mar  5 18:18 devtools
drwxr-xr-x 6 dominique dominique  4096 Mar  5 18:18 docs
drwxr-xr-x 7 dominique dominique  4096 Mar  5 18:18 dynophores
-rw-r--r-- 1 dominique dominique   887 Mar  5 18:18 setup.cfg
-rw-r--r-- 1 dominique dominique  2275 Mar  5 18:18 setup.py
-rw-r--r-- 1 dominique dominique 68611 Mar  5 18:18 versioneer.py
(test) dominique@c: ~/Documents/dynophores-master
$ pip install dynophores
ERROR: Could not find a version that satisfies the requirement dynophores
ERROR: No matching distribution found for dynophores
```
In this case, I am already _in_ the downloaded folder. Your solution does the trick by calling the `setup.py` file directly.

The "code instructions" we give in the documentation aim for going to the folder that _contains_ the downloaded folder (i.e. `dynophores-master` in my case). 
image
https://dynophores.readthedocs.io/en/latest/installing.html

Thus, the path instructions 

> 3. Navigate to ``path/to/your/location/``. 

are misleading. 

I propose to change the instructions as follows to be in-line with mentioned "code instructions":

> 3. Navigate to ``path/to/directory/that/contains/downloaded/folder``


__Case 2__
```bash
(test) dominique@c: ~/Documents
$ ls -l
drwxr-xr-x  6 dominique dominique    4096 Mar  5 18:18 dynophores-master
(test) dominique@c: ~/Documents
$ pip install dynophores
ERROR: Could not find a version that satisfies the requirement dynophores
ERROR: No matching distribution found for dynophores
```
In this case, I am at the correct directory level but my folder is called `dynophores-master` and not `dynophores`.

Thus, I propose to update

>  Run ``pip install dynophores``.

to 

>  Run ``pip install dynophores-master``.

**Comment by dominiquesydow** [comment]
What do you think about the proposed changes?
If you are good with them, would you like to make theses changes - or shall I do this? If the latter, I think I will need push-access to your fork (open for alternative suggestions).

**Comment by nadja-mansurov** [comment]
Hi @dominiquesydow 
Thank you for your response! I added you to collaborators. 
I had my issue with the macOS system and cloned, not the downloaded dynophores. I tried to perform 
> pip install dynophores
in my downloads folder. Then, when it failed, I went to the dynophores and tried to do it in the folder.

**Comment by dominiquesydow** [comment]
Hi @nadja-mansurov,

Thanks for the clarification!
Added now my proposed updates plus two notes: 
- Your `python setup.py install` option.
- A comment that the cloned repo is called `dynophores` instead of `dynophores-master` when downloaded.

What do you think?

**Comment by nadja-mansurov** [comment]
Hi @dominiquesydow, 

Thanks a lot! I think, now there is enough information about installation in docs

**Comment by dominiquesydow** [comment]
Great, thanks - then I am merging now!

**Pull request merged**
