### PR TITLE
Visualisation with d3.js

### PR DESCRIPTION
**Pull request by nadja-mansurov**
## Description
Added d3.js and simple example

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [ ] Remove circle example
- [ ] Add interactions example 

## Questions
- [ ] Question1

## Status
- [ ] First draft

### CODE REVIEW

**Comment by nadja-mansurov** [comment]
hi @dominiquesydow 
I opened a PR just to let you know, that I found a way to add d3.js :) 
It means I can work separate on js+html+css visualisation

**Comment by dominiquesydow** [comment]
Hi @nadja-mansurov,

My apologies for a late reply!

That sounds great to me - let me know if you'd like to discuss ideas! 
If you have found another project with @gwolber in the meantime, feel free to pursue something else of course.

I am currently trying to finish up this first 2D-ligand-view prototype in PR #17 (moved the code from the exploratory notebook to the package). Posting here again a screenshot of how the view looks like:
image

Most of the code ended up in the `Ligand` class (see [`dynophores.core.ligand`](https://github.com/dominiquesydow/dynophores/blob/view-2d/dynophores/core/ligand.py) module).
This [tutorial](https://github.com/dominiquesydow/dynophores/blob/view-2d/docs/tutorials/explore_view2d.ipynb) shows how to access the visualization easily.

I am ok with the visualization as it is right now but not too thrilled :) 
For the near or distant future I would be happy about a few improvements as we have discussed before. 
Started to collect ideas in this issue https://github.com/dominiquesydow/dynophores/issues/24.

**Comment by nadja-mansurov** [comment]
Hi @dominiquesydow 
Yes, I am working now on the other project. However, I guess, that adding an interactive visualization would be interesting to implement. Probably, it can be added as a "task" for the near term :)

**Comment by dominiquesydow** [comment]
Sounds good - enjoy working on your project! :)

**Pull request closed without merging**
